### ISSUE TITLE
Gerber or Kicad files

### ISSUE THREAD

**Issue by sorvis** [afarhan/sbitx#18]
Hello, 

Wondering if there we any circuit board files like Kicad or Gerber that could be used to order a board from a circuit board company? I saw the [main board pdf](https://raw.githubusercontent.com/afarhan/sbitx/main/sbitx_digital.pdf) but it doesn't seem to layout the components any.

**Comment by sorvis** [comment]
Ah, I see they might not be fully released?

```
    1) Release the board files, schematic, design files/gerbers, BoM and let someone in China clone it, walk away.
    2) Same as #1, but just sell bare PCB’s.
    3) Sell PCB’s with all SMT components installed, and a baggie of TH parts, toroids, and couple feet of magnet wire.
    4) Sell the entire thing fully assembled ($$$).

It is likely that either options 2) and 3) will be favoured by the amateur community, based on initial feedback to Martin.
```

https://ubitx.net/2018/01/24/a-top-tier-board-for-%c2%b5bitx/

**Comment by afarhan** [comment]
We have released the circuit diagram. It is left as an 'exercise to the reader' to generate kicad schematic files for this. However, the circuit is by itself GPL, the schematics are not as the derived works should not be under GPL if any other company wishes to commercialize this radio.
