### ISSUE TITLE
install.txt

### ISSUE THREAD

**Issue by oz9ny** [afarhan/sbitx#2]
I have read with interest your paper "sBITX – An open source SDR that you can hack" and couldn't resist trying.

I have installed sbitx on a fresh copy of 2020-12-02-raspios-buster-armhf-full on a rpi4.

The link  "www.fftw3.org" should be www.fftw.org

When compiling sbitx the compiler complains about missing ncurses.h

this command helps:

sudo apt-get install ncurses-dev

Looking forward to the FDIM 2021 webinar

vy 73 de oz9ny, niels

**Comment by afarhan** [comment]
good catch! the sbitx is a moving target. i will update it post FDIM once
again. I am glad that you could get it going. i have updated the git with
your fixes.
- f

**Comment by gmgaston** [comment]
I read your paper and watched video.  I have a uBITX but not ver 6 built several years ago that I thinking to use. I have lost orig docs. Where would I find older docs.  Is that going to work?.  Maybe I should just get a new ver 6 and eliminate that difference.  Any thought?.  You mention possible PCB. I’m interested 
Greg 
KD4VV

**Comment by afarhan** [comment]
All the previous versions should work. Dont invest in a new board.
Be aware that this is still under development. However, nothing like being
an early adopter. But be ready to handle things that don't work yet.

**Comment by KenSamson** [comment]
I am following this project with much interest.

The digital modes like JS8call run so well on a Raspberry pi and lend themselves very well to QRP rigs.    The idea that one could also use the wifi in a pi to then listen to internet radio stations opens up so many worlds in one place.

Having a mounting to accept filters like QRP-Labs makes could be a good synergy idea, though clearly every design choice is a tradeoff, I understand.

Some of your internet domains have expired.   Is there a good place that we should follow?

I would think if you are in need of funds to help research or source parts in bulk to help lower future costs that enough people would be willing to purchase something like a simple investors certificate from your website to just help you out.   While this may seem odd to some people, what you are doing is enabling a future generation to learn and build radios, while giving people income.   This is truly an amazing effort!

The software here is pretty amazing to follow along with.   I'm learning a lot!

**Comment by afarhan** [comment]
Ken,
I am touched by your offer. We are a community and most of us work
independently. I know that ubitx.net which was a treasure is down. The
bitx20 forum has the owner on it, if you could offer him to sponsor the
website he may prop it back up.
The sbitx is almost done except for some nominal work swapping the vfos,
rit and stacking. the main thing works beautifully.
