### ISSUE TITLE
CW Pitch

### ISSUE THREAD

**Issue by microenh** [afarhan/sbitx#24]
When you first start the application, it loads the saved CW Pitch setting. When you key down, the CW carrier is on the VFO frequency. If you change the CW Pitch, the CW carrier moves. For example, with a VFO of 3.550 MHz and a pitch of 600 Hz, when you first start the app, the CW carrier is on 3.550 MHz. If you change the pitch to 800 Hz, the CW carrier is no on 3.550.2 Hz (up 200 Hz).  If you exit the app and restart it, the VFO is still 3.550 and the pitch is 800 Hz, but the CW carrier is back on 3.550 MHz.

As I understand things, changing the CW pitch should not change the frequency of the CW carrier, just the sidetone frequency and the frequency of any received signals.

**Comment by afarhan** [comment]
This has been fixed. Can you try the updates from May 4th release? The instructions are on sbirx.net
