### ISSUE TITLE
Mode vs BW settings

### ISSUE THREAD

**Issue by ok1rp** [afarhan/sbitx#26]
When I select the mode i.e. CW and set the BW to let say 400Hz > the radio set the 400Hz BW and the label shows 400Hz too.
Now when I switch to USB the radio switches the BW to 3000Hz (widest) but label still shows 400Hz. 
On this mode USB I am going to set 2400Hz BW > the radio switches to 2400Hz correctly and label changes to 2400Hz too.
Now when switch back to CW > the radio switched again to 3000Hz (widest) BW and label still shows 2400Hz...

Summarized:
1. When mode is changed > the radio goes always to 3000Hz BW.
2. BW label does not reflect the actual BW after mode switching and staying stuck on last BW value selected.
3. After changing the mode, it does not remember the preview setting with that mode.

So, when we change mode, we save the bw for the previous mode, and restore the bandwidth for the new mode?

Yes... suggestion:
When switching from let say CW (400Hz) to USB we should save 400Hz as last time used BW linked to CW mode and restore the last time used BW on USB for newly selected USB mode.
Of course, all the time any BW can be set on currently selected mode.
Also, the BW label on upper left corner window should always shows actual BW used by radio.

If user will select the mode which was never been used before (after first install or after master reset or so) then my suggestion is to use default 3kHz widest BW for that case until new BW will be set and stored.

**short note to my last point:**
"If user will select the mode which was never been used before (after first install or after master reset or so) then my suggestion is to use default 3kHz widest BW for that case until new BW will be set and stored."

...maybe the better way is to have preset default values like 400Hz for CW, 2.4kHz for SSB and 3kHz for digi. So if user select any mode for first time (not preview value stored) then these defaults will be used.

**Comment by afarhan** [comment]
this has been fixed in the lastest code
