### ISSUE TITLE
Poor CW sending from key - nearly unusable

### ISSUE THREAD

**Issue by BrendonHills** [afarhan/sbitx#27]
Very poor CW sending from a key. I am not sure if the code is just missing dits and dahs or if it is because of a small delay in the sidetone that is causing me to miskey. By dialling down the CW timeout (QSK delay???) from 1000mS to 5mS, things improve slightly but my sending still sounds awful with missing characters. This is a major issue - CW is my only mode and I want the pleasure of sending with a key not a keyboard or macros, which actually appear to work properly. Plesae can we get this sorted or my radio becomes useless. Thanks.

**Comment by ok1rp** [comment]
I can confirm that issue. Keying from iambic paddle tested > several elements missed / cut by internal interruption (audible snapping can be heard during the keying) The minimum CW timeout available set > 50ms (not 5ms) on my #5 radio slightly helped and managed few QSOs but it is almost useless. Fix is needed.

**Comment by BrendonHills** [comment]
Latest release a little better but still not right, but no issues with a straight key - implying the paddle keyer code?

**Comment by M0mws** [comment]
Same here... not useable at present. Need to use straight key.
I do need the practice so not all bad☺️

**Comment by ok1rp** [comment]
You could also try to use iambic paddle connected through external elbug if you have one.
Sbitx V2 will be set to straight key input then.
It should work at the moment.

**Comment by afarhan** [comment]
Can you try the new keyer implemented in may 4th update?  Read the instructions on sbitx.net

**Comment by M0mws** [comment]
Ok, will text when possible. Thanks for your work👍Martin W Smith M0MWSOn 6 May 2023, at 01:32, Ashhar Farhan ***@***.***> wrote:﻿
Can you try the new keyer implemented in may 4th update?  Read the instructions on sbitx.net
