### ISSUE TITLE
FT8 mis assigns callsign

### ISSUE THREAD

**Issue by rkayakr** [afarhan/sbitx#30]
If you select a CQ that starts with "DX" then the call sign the sBITX assigns "DX" to the call sign box. The issue is the same with any text before the call sign: POTA, SOTA, VOTA, NA, JA, ...

**Comment by afarhan** [comment]
This has been fixed in the latest update. Read https://www.sbitx.net/index.php/2023/05/05/updating-the-sbitx-software-from-github/ for instructions
