### ISSUE TITLE
RF Power indicator massively out

### ISSUE THREAD

**Issue by BrendonHills** [afarhan/sbitx#33]
When drive on the sBitx reduced to 18 on 20m, i gewt 5w output. But the RF meter on the rig says 21w - a bit of a difference. I appreciate it may be way down on the list of things to do, but would be nice to get fixed if and when possible.

**Comment by afarhan** [comment]
Brandon,
This is precisely what I am working on now. As it is leading to unusually
high power outputs.
- f

**Comment by afarhan** [comment]
Check the may 4th update on how to calibrate the meter. It is on www.sbitx.net
