### ISSUE TITLE
CW keyboard does not work when log entry made

### ISSUE THREAD

**Issue by BrendonHills** [afarhan/sbitx#34]
When in CW mode, I can send from the keyboard unitl I try to use the logbook. As soon as I enter a call into the log, the keyboard will no longer send CW. Thanks

**Comment by afarhan** [comment]
Brendon,
Touch back on the cw decode window for now.

**Comment by BrendonHills** [comment]
Great, got it thanks!

**Comment by afarhan** [comment]
You have to shift the focus back to the cw entry window. Touch of click on the cw decodes window and type away
