### ISSUE TITLE
RX suddenly stops

### ISSUE THREAD

**Issue by BrendonHills** [afarhan/sbitx#36]
Periodically, RX just stops. The Waterfall goes suddenly blank, nothing is received. Changing bands and back again does not help.
Quitting SBitx screen and restarting does not help.
Sometimes what look like birdies appear on the screen but no external signals.
A soft re-boot of the Raspberry Pi does not resolve it.
A hard reset (power cycle) seems to restore it.

**Comment by ok1rp** [comment]
Strange. What sn of V2 unit pls and do you have stock build version on SD card?

**Comment by BrendonHills** [comment]
> Strange. What sn of V2 unit u hve pls and do you hve stock build version on SD card or any build mod from arrival?

Hi, Serial number 0087. I have the supplied SD card and I yesterday did the ./update as suggested by Farhan re. the looging issue.  It does not happen every time, but I have noticed it happen if I have left the radio running in the background whilst getting on with other jobs and coming back maybe an hour or so later. Sometime it happens whilst unattended. Sometimes it happens whilst tuning. I do not know if it is linked to my earlier issue re. lagging display. 

Hope that helps.

Daimon.

**Comment by afarhan** [comment]
the v3 has fixed this
