### ISSUE TITLE
Blurred top right of the display.

### ISSUE THREAD

**Issue by g8kig** [afarhan/sbitx#42]
On my **sbitx**, there are several fields overlayed on each other where the B vfo is displayed.
![IMG_20230503_175921](https://user-images.githubusercontent.com/7365848/235988530-167fa99e-92ab-43ce-9b69-bcf32caa9440.jpg)

**Comment by afarhan** [comment]
The gtk user interface is being deprecated and the web Ui is where the new fixes will be.

**Comment by g8kig** [comment]
That's a shame. I have no wish to incur the overhead of a web browser to operate my radio.
