### ISSUE TITLE
Are these allocations correct? (sbitx_sound.c)

### ISSUE THREAD

**Issue by g8kig** [afarhan/sbitx#44]
`static snd_pcm_uframes_t buff_size = 8192; /* Periodsize (bytes) */
`
```
  //we allocate enough for two channels of int32_t sized samples	
  data_in = (int32_t *)malloc(buff_size * 2);
  line_out = (int32_t *)malloc(buff_size * 2);
  data_out = (int32_t *)malloc(buff_size * 2);
  input_i = (int32_t *)malloc(sizeof(buff_size * 2);
  output_i = (int32_t *)malloc(sizeof(buff_size * 2);
  input_q = (int32_t *)malloc(sizeof(buff_size * 2);
  output_q = (int32_t *)malloc(sizeof(buff_size * 2);

```
The comment for buf size says bytes but the allocations are cast to an int32_t* type.
Should each allocation be multiplied by 'sizeof(int32_t)?

**Comment by afarhan** [comment]
We use buffers of 2048 samples, each sample is two (channels) of 32 bit
integers, That makes the buffer size to be 2048x8 = 16384 bytes each.
Even 8192 x 2 makes it come to 16384 bytes.
I guess it is alright. What do you think?

**Comment by g8kig** [comment]
So the buff_size should be 2048*sizeof(int32_t).
I was confused by the magic number.
Also the 2 multiplier could have been a num_channels = 2 constant.
Thanks.
