### ISSUE TITLE
real time clock set at 2000/01/01 

### ISSUE THREAD

**Issue by m0prf** [afarhan/sbitx#45]
real time clock internal board not right.
set 2000/01/01 i have no way to set this can there be an update so it does

jeffrey

**Comment by g8kig** [comment]
Please check you have fitted a CR2032 battery to the RTC chip (carefully note the placement of the RTC board on the socket when removing and refitting) and then run

`sudo apt install ntp ntpdate ntpstat`

**Comment by m0prf** [comment]
thank you g8kig
looks as i was able to do it on first try,maybe i will be a coder one day..

tnx jeffrey M0PRF
