### ISSUE TITLE
Enhancement: 60m band support

### ISSUE THREAD

**Issue by exDB2OO** [afarhan/sbitx#47]
Currently the sBITX is supporting all SW bands except 60m.
At least in Europe 60m is pretty interesting for FT8 as there is a general output power limit (essentially EIRP limit) that would most probably fit to the sBITX output power. 
This means that all stations you hear, you will also be able to reach, as there won't be a 20Watts to 1.5kW mismatch as on the other bands ;-)
This enhancement will hopefully just be a SW change and the existing LP filters can be reused.

**Comment by RAndrewThomas** [comment]
I don't see any problem on the software side, nor on the receive side.  On transmit, the LPF to use seems to be "C" which is currently used for 40m and 30m (10.150 MHz highest).  60m 2nd harmonic will range from 10.6 to 10.8 MHz which *may* be a problem for that filter - it may not suppress that 2nd harmonic well enough.

I have the equipment to test the filter frequency response, but I'm afraid of the PCB hacking required to inject an isolated, calibrated RF signal just through the LPF.  Just programming the tuning to cover the range can tell me something by measuring the SWR and power, but my sbitx v2 is untrustworthy on that point.  I probably need to convert it to v3.
