### ISSUE TITLE
Suggestion: Define max RF gain per mode

### ISSUE THREAD

**Issue by packman2008** [afarhan/sbitx#51]
It's probably not advisable to run FT8 with RF gain set to 100. It would be useful to be able to define a default gain for each mode. For example, when I switch to FT8 change the gain to a user defined value, e.g. 30. That avoids switching from a mode where you can more safely use a higher gain to one that really needs a lower gain and forgetting to change the gain after the switch. Maybe have an extra option of either 'make this the maximum possible gain for this mode' or 'allow me to increase the gain after setting the default'.

**Comment by afarhan** [comment]
There is another pull request to implement AGC using RF/IF gain. that maywork better. In anycase, we won't see much loss of dynamic range as we use a 24-bit codec with more headroom that useful. Our limitation is the front-end, and IF gain control does not change the dynamic range of the front end
