### ISSUE TITLE
Move RTC support to the OS level

### ISSUE THREAD

**Issue by microenh** [afarhan/sbitx#53]
Remove code for the RTC from the sBitx code and instead let the Raspberry Pi OS manage it (it's trivial) and just let sBitx use the system time. For example, I have the RTC set up at the OS level and I also run chrony. Chrony can also manage time from a GPS dongle, if available, and gracefully manages multiple possible time sources (RTC, GPS, NTP), using whatever's available. It also automatically updates the RTC time when it gets time from a more accurate source.

**Comment by afarhan** [comment]
Unfortunately, the WM8731 audio codec does not like anything else on the I2C bus that is can be accessed by the operating system. Hence, we had to move Si5351 and the RTC to a bit-banged bus
