### ISSUE TITLE
character "6" is not sent in cw from keyboard 

### ISSUE THREAD

**Issue by g6zbv** [afarhan/sbitx#59]
character "6" is not sent in cw from keyboard

**Comment by mbridak** [comment]
I'm sorry, I can't reproduce this.

**Comment by g6zbv** [comment]
Hi

I think you’ll find it sends “H” instead its missing the first dash


Cheers

Adrian

**Comment by MolKa51** [comment]
Adrian,
in the BITX20 group, in post #104223, this bug has been fixed, which is in use with v2 sBitx. In the above message, a typo occurred in the modem.c file. If you use v3, it is fixed there and you can find the fix in the modem_cw.c file.

**Comment by afarhan** [comment]
This is fixed in v3
