### ISSUE TITLE
sbitx build error with the new version 3

### ISSUE THREAD

**Issue by g8kig** [afarhan/sbitx#60]
I had to install libopus using the following command line before build was successful:

'sudo apt install -y libopus-dev'

It might be possible to add it to the build script?

If the update shell script is run and an error occurs with say the git command it goes on to run the build again without any checking.
You might think it has updated when it hasn't.
The fix is to add

    set -e

line at the top of the script.
It is always good practice to check return codes in bash scripts.

**Comment by afarhan** [comment]
libopus has been removed. it wasn't required at all
