### ISSUE TITLE
File modem_cw.c function cw_tx_get_sample() line 359. Incomprehensible code.

### ISSUE THREAD

**Issue by g8kig** [afarhan/sbitx#62]
```
		if (cw_tone.freq_hz != get_pitch())
			(&cw_tone, get_pitch(), 0);  <<< ???
```
Not sure what the intention of this comma expression is. The left hand and right hand operands have no effect.

**Comment by afarhan** [comment]
it was supposed to call vfo_start, thanks. fixed it
