### ISSUE TITLE
User settings written to disk very, very often

### ISSUE THREAD

**Issue by n1ai** [afarhan/sbitx#74]
https://github.com/afarhan/sbitx/blob/7abd77da8b45138bad5900b0b33563ba25013d57/sbitx_gtk.c#L1291

The code that refers to `last_save_at` is:

![image](https://github.com/afarhan/sbitx/assets/99760360/9eeccb6f-a257-4f7d-8c83-b6d878217b91)

Yet the code never sets it after it does update the file.

This means we write the user settings to disk very, very often, like every time you move the tuning or volume knob.

Adding a line of code to set the variable to `now` at the end of the function is a fix:

![image](https://github.com/afarhan/sbitx/assets/99760360/4aa3abe4-64b3-4338-93c3-8b41259d9713)

Yet maybe only writing once every 30 seconds is not often enough?

**Comment by RAndrewThomas** [comment]
I like your bugfix and have incorporated in my own fork already.  My opinion on the auto-save interval: 30 seconds is fine or even faster than necessary.

With a save on normal exit too, I think most folks would understand that after a crash all bets are off.

It might be nice to catch SIGTERM and save user settings on the way out (after CTRL-C, etc), but that's probably unnecessarily fancy.

-n5rgn

**Comment by n1ai** [comment]
> I like your bugfix and have incorporated in my own fork already. My opinion on the auto-save interval: 30 seconds is fine or even faster than necessary. Could even make the user settings auto-save interval a user setting ;) With reasonable bounds enforced.
> 
> With a save on normal exit too, I think most folks would understand that after a crash all bets are off.
> 
> It might be nice to catch SIGTERM and save user settings on the way out (after CTRL-C, etc), but that's probably unnecessarily fancy.
> 
> -n5rgn

I'm glad you like the bug fix.

https://github.com/afarhan/sbitx/pull/75 also has the fix, in a pull request ready to go.

It's an improvement on what is in the code code, but overall I think perhaps the best strategy is to save on band switch (since that's when the band stack gets updated) and save on exit. 

I'll leave this issue opened till someone gets a chance to do something better.

**Comment by afarhan** [comment]
this was fixed by v3.02
