### ISSUE TITLE
Tuning knob switch as step change focus

### ISSUE THREAD

**Issue by n1ai** [afarhan/sbitx#76]
I think using the tuning knob switch to change the step value is a good idea.

See discussion [here](https://groups.io/g/BITX20/topic/103453298#107352) on this and related topics.

**Comment by RAndrewThomas** [comment]
I think it is an excellent idea - intuitive, convenient and similar to other radios.  I also agree with others' suggestions for debounce or "ON_RELEASE" style handling.

**Comment by afarhan** [comment]
I am reserving the tuning knob switch for navigating between fields (when we come to that). We may have to make versions of sbitx that work on non-touch screens and having the tuning know toggle between tuning and field selection maybe more useful. I am adding this to the to-do list.
