### ISSUE TITLE
3.0 update script fails to update because git sees sbitx binary as a local change

### ISSUE THREAD

**Issue by MaggieLeber** [afarhan/sbitx#89]
Am I missing something dumb/simple here? 
New `sbitx` user just received radio...wanted to get current, so: 

```pi@sbitx:~ $ cd sbitx
pi@sbitx:~/sbitx $ ./update
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Thu 01 Feb 2024 10:26:52 PM America
Updating 7abd77d..a60313c
error: Your local changes to the following files would be overwritten by merge:
        sbitx
Please commit your changes or stash them before you merge.
Aborting
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Thu 01 Feb 2024 10:26:52 PM America
database is intact
compiling sbitx version v3.0 in /home/pi/sbitx
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

I mean, I can see how to circumvent this, just hide the binary someplace that git won't see, but it kind of surprised me and made me wonder if I'm doing something dumb. 

Thanks....Maggie K3XS

**Comment by n1ai** [comment]
> I mean, I can see how to circumvent this, just hide the binary someplace that git won't see, but it kind of surprised me and made me wonder if I'm doing something dumb.

No, you are not doing something dumb.  

Any local build creates a new sbitx binary, so the next run of ./update fails for the reason you give.

Very little thought has been given to release strategy, upgrade and downgrade procedures, packaging, etc.

See also: https://groups.io/g/BITX20/message/95534

**Comment by MaggieLeber** [comment]
Cool, and thanks. Since a fix is on the way, I'll close this bug.
